import type {
  AssetKind,
  EventBundle,
  EventCounts,
  EventSummary,
  EvaluationWorkspaceResponse,
  OrganizerAgendaResponse,
  OrganizerSession,
  PublicScheduleResponse,
  PublicSessionsResponse,
  PublicSpeakersResponse,
  ResourcePage,
  Session,
  SessionFormat,
  Speaker,
  SpeakerAsset,
  SpeakerTask,
  SpeakerPortalProposal,
  ReviewerQueueResponse,
  SaveEvaluationRoundRequest,
  SaveRoundReviewerRequest,
  SubmitReviewRequest,
  CreateEventRequest,
  UpdateEventSettingsRequest,
  OutboxMessage,
  CreateTrackRequest,
  CreateRoomRequest,
  CreateFormFieldRequest,
  SubmissionListItem,
  TaskDefinition,
} from "../../shared/contracts";

/**
 * Persistence boundary. Route handlers and domain code talk to this interface
 * only — never to D1 or Airtable directly. D1Repo is the complete default;
 * AirtableRepo implements the documented operational proof subset.
 *
 * Contract rules:
 * - IDs for new rows are generated by the CALLER and passed in, so the repo
 *   stays deterministic and testable. Upserts may return a pre-existing id.
 * - All timestamps are passed in as ISO strings (injected clock).
 */
export interface SpeakerOpsRepo {
  /** Cheap connectivity probe for /api/health. */
  health(): Promise<boolean>;

  listEvents(): Promise<EventSummary[]>;
  getEventBySlug(slug: string): Promise<EventBundle | null>;
  getPublicSchedule(slug: string): Promise<PublicScheduleResponse | null>;
  getPublicSessions(slug: string): Promise<PublicSessionsResponse | null>;
  getPublicSpeakers(slug: string): Promise<PublicSpeakersResponse | null>;

  /**
   * Public CFP intake. Upserts the speaker by (event, email) — a returning
   * speaker keeps their id — then inserts the submission and the primary
   * speaker link. Returns the full organizer-view list item.
   */
  createCfpSubmission(input: CreateCfpSubmissionInput): Promise<SubmissionListItem>;
  listSubmissions(eventId: string): Promise<SubmissionListItem[]>;
  getSubmissionById(id: string): Promise<SubmissionListItem | null>;
  decideSubmission(input: DecideSubmissionInput): Promise<SubmissionDecisionResult>;
  getOrganizerAgenda(eventId: string): Promise<OrganizerAgendaResponse>;
  createDirectSession(input: CreateDirectSessionInput): Promise<OrganizerSession>;
  updateSession(input: UpdateSessionInput): Promise<OrganizerSession>;
  upsertAgendaSlot(input: UpsertAgendaSlotInput): Promise<OrganizerAgendaResponse>;
  publishAgenda(eventId: string, now: string): Promise<string>;
  countsForEvent(eventId: string): Promise<EventCounts>;

  getSpeakerById(id: string): Promise<Speaker | null>;
  getSpeakerPortalByToken(token: string): Promise<SpeakerPortalBundle | null>;
  updateSpeakerProfile(input: UpdateSpeakerProfileInput): Promise<SpeakerPortalBundle>;
  updateSpeakerTask(input: UpdateSpeakerTaskInput): Promise<SpeakerPortalBundle>;
  updateSpeakerProposal(input: UpdateSpeakerProposalInput): Promise<SpeakerPortalBundle>;
  getEvaluationWorkspace(eventId: string): Promise<EvaluationWorkspaceResponse>;
  saveEvaluationRound(input: SaveEvaluationRoundInput): Promise<void>;
  saveRoundReviewer(input: SaveRoundReviewerInput): Promise<void>;
  saveAssignments(input: SaveAssignmentsInput): Promise<void>;
  autoDistributeAssignments(roundId: string, now: string): Promise<void>;
  getReviewerQueue(token: string): Promise<ReviewerQueueResponse | null>;
  submitReviewerScorecard(input: SubmitReviewerScorecardInput): Promise<void>;
  createEvent(input: CreateEventInput): Promise<EventBundle>;
  updateEventSettings(input: UpdateEventSettingsInput): Promise<EventBundle>;
  createTrack(input: CreateTrackInput): Promise<EventBundle>;
  createRoom(input: CreateRoomInput): Promise<EventBundle>;
  createFormField(input: CreateFormFieldInput): Promise<EventBundle>;
  simulateCommunication(input: SimulateCommunicationInput): Promise<void>;
  queueDueTaskReminders(now: string, dueBefore: string): Promise<QueueDueTaskRemindersResult>;
  listMessages(eventId: string): Promise<OutboxMessage[]>;
  createSpeakerAsset(input: CreateSpeakerAssetInput): Promise<SpeakerAsset>;
  getSpeakerAssetById(id: string): Promise<SpeakerAsset | null>;
}

export interface UpdateSessionInput {
  sessionId: string;
  eventId: string;
  title: string;
  abstract: string;
  now: string;
}

export interface DecideSubmissionInput {
  submissionId: string;
  decision: "approve" | "maybe" | "deny";
  /** Internal note; persisted as a committee review when non-empty. */
  reasoning?: string;
  /** Who the note is filed under; empty means the default Organizer. */
  reviewerName?: string;
  /** Approve only: program title/abstract, when retitled on approval. */
  sessionTitle?: string;
  sessionAbstract?: string;
  now: string;
}

export interface SubmissionDecisionResult {
  submission: SubmissionListItem;
  session: Session | null;
  reusedSession: boolean;
}

export interface CreateDirectSessionInput {
  id: string;
  eventId: string;
  title: string;
  abstract: string;
  format: SessionFormat;
  trackId: string | null;
  speakerIds: string[];
  now: string;
}

export interface UpsertAgendaSlotInput {
  id: string;
  eventId: string;
  sessionId: string;
  roomId: string;
  startsAt: string;
  endsAt: string;
  now: string;
}

export interface UpdateSpeakerProfileInput {
  speakerId: string;
  name: string;
  company: string | null;
  title: string | null;
  bio: string | null;
  location: string | null;
  socials: Speaker["socials"];
  now: string;
}

export interface UpdateSpeakerTaskInput {
  speakerId: string;
  taskId: string;
  status: "pending" | "complete";
  now: string;
}

export interface SimulateCommunicationInput {
  messageId: string;
  attemptId: string;
  eventId: string;
  speakerId: string | null;
  toEmail: string;
  subject: string;
  bodyMd: string;
  now: string;
}

export interface QueueDueTaskRemindersResult {
  queued: number;
  taskIds: string[];
}

export interface SaveEvaluationRoundInput {
  eventId: string;
  planId: string;
  roundId: string;
  data: SaveEvaluationRoundRequest;
  criterionIds: string[];
}

export interface SaveRoundReviewerInput extends SaveRoundReviewerRequest {
  roundId: string;
  token: string;
  now: string;
}

export interface SaveAssignmentsInput {
  roundId: string;
  reviewerEmail: string;
  submissionIds: string[];
  now: string;
}

export interface SubmitReviewerScorecardInput extends SubmitReviewRequest {
  id: string;
  token: string;
  roundId: string;
  submissionId: string;
  now: string;
  recuse?: boolean;
}

export interface CreateEventInput extends CreateEventRequest {
  eventId: string;
  formId: string;
  planId: string;
  now: string;
}

export interface UpdateEventSettingsInput extends UpdateEventSettingsRequest {
  eventId: string;
  now: string;
}

export interface CreateTrackInput extends CreateTrackRequest {
  id: string;
  eventId: string;
}

export interface CreateRoomInput extends CreateRoomRequest {
  id: string;
  eventId: string;
}

export interface CreateFormFieldInput extends CreateFormFieldRequest {
  id: string;
  ruleId: string | null;
  eventId: string;
  formId: string;
}

export interface SpeakerPortalBundle {
  event: EventSummary;
  speaker: Speaker;
  sessions: SpeakerPortalSession[];
  proposals: SpeakerPortalProposal[];
  cfp: EventBundle["cfp"];
  tasks: SpeakerPortalTask[];
  assets: SpeakerAsset[];
  resources: ResourcePage[];
}

export interface UpdateSpeakerProposalInput {
  speakerId: string;
  submissionId: string;
  title: string;
  abstract: string;
  answers: Record<string, unknown>;
  now: string;
}

export interface SpeakerPortalSession {
  id: string;
  title: string;
  abstract: string;
  format: SessionFormat;
  startsAt: string | null;
  endsAt: string | null;
  roomName: string | null;
}

export interface SpeakerPortalTask {
  task: SpeakerTask;
  definition: TaskDefinition;
}

export interface CreateCfpSubmissionInput {
  eventId: string;
  formId: string;
  trackId: string;
  title: string;
  abstract: string;
  format: SessionFormat;
  /** Already pruned to visible, known form fields. */
  answers: Record<string, unknown>;
  speaker: {
    name: string;
    email: string;
    company?: string;
    title?: string;
    bio?: string;
  };
  coSpeakers: Array<{
    id: string;
    name: string;
    email: string;
    company?: string;
    title?: string;
    bio?: string;
  }>;
  /** Id to use IF the speaker is new; ignored when the email already exists. */
  speakerId: string;
  submissionId: string;
  now: string;
}

export interface CreateSpeakerAssetInput {
  id: string;
  speakerId: string;
  kind: AssetKind;
  filename: string;
  contentType: string;
  sizeBytes: number;
  r2Key: string;
  uploadedAt: string;
}
