import { useState } from "react";
import type { EventBundle } from "../../../shared/contracts";
import { Badge, Button, Card, ErrorBanner, Field, Input, PageHeader, Select, Spinner, Textarea } from "../../components/ui";
import { ApiRequestError, apiClient } from "../../lib/api";
import { useAsync } from "../../lib/useAsync";
import { useAdminContext } from "./AdminLayout";

function localValue(iso: string | null): string { if (!iso) return ""; const date = new Date(iso); return new Date(date.getTime() - date.getTimezoneOffset() * 60_000).toISOString().slice(0, 16); }
function toIso(value: string): string | null { return value ? new Date(value).toISOString() : null; }

export function Settings() {
  const { eventSlug } = useAdminContext();
  const { data: loaded, error, loading, reload } = useAsync(() => apiClient.eventBundle(eventSlug), [eventSlug]);
  const [override, setOverride] = useState<EventBundle | null>(null); const [notice, setNotice] = useState<string | null>(null);
  if (loading) return <Spinner label="Loading event settings" />;
  if (error || !loaded) return <ErrorBanner message={error?.message ?? "Event settings unavailable."} />;
  const data = override ?? loaded;
  return <div><PageHeader title="Event & CFP settings" subtitle="Configure the submission window, custom fields, tracks, and event portfolio." actions={<Button variant="secondary" onClick={() => { setOverride(null); reload(); }}>Refresh</Button>} />{notice ? <p role="status" className="mb-4 rounded-lg border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800">{notice}</p> : null}<div className="grid gap-5 xl:grid-cols-2"><CfpSettings data={data} onUpdated={(next) => { setOverride(next); setNotice("CFP settings saved. Speaker proposal editing now follows this window."); }} /><Tracks data={data} onUpdated={(next) => { setOverride(next); setNotice("Track added and immediately available on the public CFP."); }} /><FormBuilder data={data} onUpdated={(next) => { setOverride(next); setNotice("Custom field added. Client and API validation share the same rules."); }} /><CreateEvent onCreated={(name) => setNotice(`${name} created. Reload the organizer console to select it.`)} /></div></div>;
}

function CfpSettings({ data, onUpdated }: { data: EventBundle; onUpdated: (data: EventBundle) => void }) {
  const cfp = data.cfp; const [isOpen, setIsOpen] = useState(cfp?.form.isOpen ?? false); const [opensAt, setOpensAt] = useState(localValue(cfp?.form.opensAt ?? null)); const [closesAt, setClosesAt] = useState(localValue(cfp?.form.closesAt ?? null)); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  async function save(e: React.FormEvent) { e.preventDefault(); setBusy(true); setError(null); try { onUpdated(await apiClient.updateEventSettings(data.event.slug, { cfpIsOpen: isOpen, cfpOpensAt: toIso(opensAt), cfpClosesAt: toIso(closesAt) })); } catch (caught) { setError(caught instanceof ApiRequestError ? caught.message : "Settings could not be saved."); } finally { setBusy(false); } }
  return <Card className="p-5"><h2 className="text-base font-semibold">CFP window</h2><form onSubmit={save} className="mt-4 grid gap-4"><label className="flex gap-2 text-sm"><input type="checkbox" checked={isOpen} onChange={(e) => setIsOpen(e.target.checked)} /> CFP enabled</label><Field label="Opens"><Input type="datetime-local" value={opensAt} onChange={(e) => setOpensAt(e.target.value)} /></Field><Field label="Closes"><Input type="datetime-local" value={closesAt} onChange={(e) => setClosesAt(e.target.value)} /></Field>{error ? <ErrorBanner message={error} /> : null}<Button type="submit" disabled={busy || !cfp}>{busy ? "Saving…" : "Save CFP window"}</Button></form></Card>;
}

function Tracks({ data, onUpdated }: { data: EventBundle; onUpdated: (data: EventBundle) => void }) {
  const [name, setName] = useState(""); const [description, setDescription] = useState(""); const [color, setColor] = useState("#c7d2fe"); const [error, setError] = useState<string | null>(null);
  async function add(e: React.FormEvent) { e.preventDefault(); setError(null); try { onUpdated(await apiClient.createTrack(data.event.slug, { name, description: description || null, color })); setName(""); setDescription(""); } catch (caught) { setError(caught instanceof ApiRequestError ? caught.message : "Track could not be added."); } }
  return <Card className="p-5"><h2 className="text-base font-semibold">Tracks & formats</h2><div className="mt-3 flex flex-wrap gap-2">{data.tracks.map((track) => <Badge key={track.id} tone="indigo">{track.name}</Badge>)}</div><p className="mt-3 text-xs text-zinc-500">Formats are fixed, honest program types: Talk, Workshop, Panel, Lightning, and Keynote.</p><form onSubmit={add} className="mt-4 space-y-3 border-t border-zinc-100 pt-4"><Field label="New track name" required><Input value={name} onChange={(e) => setName(e.target.value)} required /></Field><Field label="Description"><Textarea value={description} onChange={(e) => setDescription(e.target.value)} /></Field><Field label="Color"><Input type="color" value={color} onChange={(e) => setColor(e.target.value)} /></Field>{error ? <ErrorBanner message={error} /> : null}<Button type="submit">Add track</Button></form></Card>;
}

function FormBuilder({ data, onUpdated }: { data: EventBundle; onUpdated: (data: EventBundle) => void }) {
  const [label, setLabel] = useState(""); const [key, setKey] = useState(""); const [type, setType] = useState<"text" | "select" | "checkbox">("text"); const [required, setRequired] = useState(false); const [options, setOptions] = useState(""); const [conditional, setConditional] = useState(false); const [conditionValue, setConditionValue] = useState("workshop"); const [error, setError] = useState<string | null>(null);
  async function add(e: React.FormEvent) { e.preventDefault(); setError(null); try { const next = await apiClient.createFormField(data.event.slug, { label, key, fieldType: type, required, helpText: null, options: type === "select" ? options.split(",").map((item) => item.trim()).filter(Boolean) : null, condition: conditional ? { sourceFieldKey: "format", operator: "equals", values: [conditionValue] } : null }); onUpdated(next); setLabel(""); setKey(""); } catch (caught) { setError(caught instanceof ApiRequestError ? caught.message : "Field could not be added."); } }
  return <Card className="p-5"><h2 className="text-base font-semibold">CFP form builder</h2><div className="mt-3 space-y-2">{data.cfp?.fields.map((field) => <div key={field.id} className="flex justify-between rounded-lg bg-zinc-50 px-3 py-2 text-sm"><span>{field.label}{field.required ? " *" : ""}</span><span className="text-zinc-500">{field.fieldType}</span></div>)}</div><form onSubmit={add} className="mt-4 space-y-3 border-t border-zinc-100 pt-4"><Field label="Label" required><Input value={label} onChange={(e) => { setLabel(e.target.value); setKey(e.target.value.toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_|_$/g, "")); }} required /></Field><Field label="Field key" required><Input value={key} onChange={(e) => setKey(e.target.value)} required /></Field><Field label="Type"><Select value={type} onChange={(e) => setType(e.target.value as typeof type)}><option value="text">Text</option><option value="select">Select</option><option value="checkbox">Checkbox</option></Select></Field>{type === "select" ? <Field label="Options" help="Comma-separated"><Input value={options} onChange={(e) => setOptions(e.target.value)} required /></Field> : null}<label className="flex gap-2 text-sm"><input type="checkbox" checked={required} onChange={(e) => setRequired(e.target.checked)} /> Required</label><label className="flex gap-2 text-sm"><input type="checkbox" checked={conditional} onChange={(e) => setConditional(e.target.checked)} /> Show only for a format</label>{conditional ? <Field label="Show when format is"><Select value={conditionValue} onChange={(e) => setConditionValue(e.target.value)}><option value="talk">Talk</option><option value="workshop">Workshop</option><option value="panel">Panel</option><option value="lightning">Lightning</option><option value="keynote">Keynote</option></Select></Field> : null}{error ? <ErrorBanner message={error} /> : null}<Button type="submit">Add custom field</Button></form></Card>;
}

function CreateEvent({ onCreated }: { onCreated: (name: string) => void }) {
  const [name, setName] = useState(""); const [slug, setSlug] = useState(""); const [startsOn, setStartsOn] = useState("2028-10-10"); const [endsOn, setEndsOn] = useState("2028-10-12"); const [timezone, setTimezone] = useState("America/Los_Angeles"); const [error, setError] = useState<string | null>(null);
  async function create(e: React.FormEvent) { e.preventDefault(); setError(null); try { const created = await apiClient.createEvent({ name, slug, startsOn, endsOn, timezone }); onCreated(created.event.name); setName(""); setSlug(""); } catch (caught) { setError(caught instanceof ApiRequestError ? caught.message : "Event could not be created."); } }
  return <Card className="p-5"><h2 className="text-base font-semibold">Create another event</h2><p className="mt-1 text-sm text-zinc-500">New events get their own CFP and evaluation plan, isolated from this event.</p><form onSubmit={create} className="mt-4 space-y-3"><Field label="Event name" required><Input value={name} onChange={(e) => { setName(e.target.value); setSlug(e.target.value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "")); }} required /></Field><Field label="URL slug" required><Input value={slug} onChange={(e) => setSlug(e.target.value)} required /></Field><div className="grid grid-cols-2 gap-3"><Field label="Starts" required><Input type="date" value={startsOn} onChange={(e) => setStartsOn(e.target.value)} /></Field><Field label="Ends" required><Input type="date" value={endsOn} onChange={(e) => setEndsOn(e.target.value)} /></Field></div><Field label="Timezone" required><Input value={timezone} onChange={(e) => setTimezone(e.target.value)} /></Field>{error ? <ErrorBanner message={error} /> : null}<Button type="submit">Create event</Button></form></Card>;
}
