import { useState } from "react";
import { Link, useParams } from "react-router";
import type { ReviewerQueueResponse, ReviewerQueueSubmission } from "../../shared/contracts";
import { Badge, Button, Card, ErrorBanner, Field, Select, Spinner, Textarea } from "../components/ui";
import { ApiRequestError, apiClient } from "../lib/api";
import { useAsync } from "../lib/useAsync";

export function ReviewerPortal() {
  const { token = "" } = useParams();
  const { data: loaded, error, loading } = useAsync(() => apiClient.reviewerQueue(token), [token]);
  const [override, setOverride] = useState<ReviewerQueueResponse | null>(null);
  if (loading) return <div className="flex min-h-dvh items-center justify-center"><Spinner label="Loading reviewer queue" /></div>;
  if (error || !loaded) return <div className="mx-auto max-w-2xl px-6 py-20"><ErrorBanner message={error?.message ?? "Reviewer queue not found."} /><Link className="mt-4 block text-sm text-accent" to="/">Back to Lectern</Link></div>;
  const data = override ?? loaded;
  const complete = data.assignments.filter((item) => item.existingReview).length;
  return <div className="min-h-dvh bg-zinc-50"><header className="border-b border-zinc-200 bg-white"><div className="mx-auto max-w-5xl px-6 py-6"><Link to="/" className="text-xs font-medium text-zinc-500">Lectern reviewer portal</Link><h1 className="mt-2 text-2xl font-semibold">{data.reviewer.name}'s review queue</h1><p className="mt-1 text-sm text-zinc-500">{complete} of {data.assignments.length} assigned scorecards complete. Only your assigned submissions are shown.</p></div></header><main className="mx-auto max-w-5xl space-y-5 px-6 py-8">{data.assignments.length === 0 ? <Card className="p-8 text-center"><h2 className="font-semibold">Nothing left in your actionable queue</h2><p className="mt-2 text-sm text-zinc-500">You may be complete, recused, or waiting for an open round.</p></Card> : data.assignments.map((assignment) => <Scorecard key={`${assignment.roundId}-${assignment.id}`} token={token} assignment={assignment} onUpdated={setOverride} />)}</main></div>;
}

function Scorecard({ token, assignment, onUpdated }: { token: string; assignment: ReviewerQueueSubmission; onUpdated: (queue: ReviewerQueueResponse) => void }) {
  const [scores, setScores] = useState<Record<string, number>>(assignment.existingReview?.scores ?? {});
  const [recommendation, setRecommendation] = useState<"accept" | "waitlist" | "reject">(
    assignment.existingReview?.recommendation === "waitlist" || assignment.existingReview?.recommendation === "reject"
      ? assignment.existingReview.recommendation : "accept",
  );
  const [comment, setComment] = useState(assignment.existingReview?.comment ?? "");
  const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null);
  async function submit(event: React.FormEvent) { event.preventDefault(); setBusy(true); setError(null); setNotice(null); try { onUpdated(await apiClient.submitReview(token, assignment.roundId, assignment.id, { scores, recommendation, comment })); setNotice("Scorecard saved. You can reopen and update it until the round closes."); } catch (caught) { setError(caught instanceof ApiRequestError ? caught.message : "Scorecard could not be saved."); } finally { setBusy(false); } }
  async function recuse() { setBusy(true); setError(null); try { onUpdated(await apiClient.recuseReview(token, assignment.roundId, assignment.id)); } catch (caught) { setError(caught instanceof ApiRequestError ? caught.message : "Recusal could not be saved."); } finally { setBusy(false); } }
  return <Card className="p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex gap-2"><Badge tone="indigo">{assignment.roundName}</Badge>{assignment.blindMode ? <Badge tone="violet">Blind review</Badge> : null}{assignment.existingReview ? <Badge tone="emerald">Complete</Badge> : <Badge tone="amber">Assigned</Badge>}</div><h2 className="mt-2 text-lg font-semibold">{assignment.title}</h2><p className="mt-1 text-xs text-zinc-500">{assignment.trackName ?? "Unassigned track"} · {assignment.format}</p></div><Button variant="ghost" disabled={busy} onClick={() => void recuse()}>Recuse — conflict of interest</Button></div><p className="mt-4 text-sm leading-6 text-zinc-700">{assignment.abstract}</p>{assignment.speakers ? <div className="mt-4 rounded-lg bg-zinc-50 p-3"><p className="text-xs font-semibold uppercase text-zinc-500">Presenters</p>{assignment.speakers.map((speaker) => <p key={speaker.speakerId} className="mt-1 text-sm"><span className="font-medium">{speaker.name}</span>{speaker.company ? ` · ${speaker.company}` : ""}{speaker.role === "co_speaker" ? ` · ${speaker.roleLabel?.trim() || "co-speaker"}` : ""}</p>)}</div> : null}<form onSubmit={submit} className="mt-5 grid gap-4 border-t border-zinc-100 pt-5 sm:grid-cols-2">{assignment.criteria.map((criterion) => <Field key={criterion.id} label={`${criterion.label} (1–${criterion.maxScore}, weight ${criterion.weight})`} required><Select value={scores[criterion.key] ?? ""} required onChange={(event) => setScores((current) => ({ ...current, [criterion.key]: Number(event.target.value) }))}><option value="">Choose score…</option>{Array.from({ length: criterion.maxScore }, (_, index) => index + 1).map((score) => <option key={score} value={score}>{score}</option>)}</Select></Field>)}<Field label="Recommendation" required><Select value={recommendation} onChange={(event) => setRecommendation(event.target.value as typeof recommendation)}><option value="accept">Accept</option><option value="waitlist">Maybe / waitlist</option><option value="reject">Reject</option></Select></Field><div className="sm:col-span-2"><Field label="Comments"><Textarea rows={5} value={comment} onChange={(event) => setComment(event.target.value)} /></Field></div>{error ? <div className="sm:col-span-2"><ErrorBanner message={error} /></div> : null}{notice ? <p role="status" className="sm:col-span-2 text-sm font-medium text-emerald-700">{notice}</p> : null}<div className="sm:col-span-2"><Button type="submit" disabled={busy}>{busy ? "Saving…" : assignment.existingReview ? "Update scorecard" : "Submit scorecard"}</Button></div></form></Card>;
}
